version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: docker:18.09.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build .
